name: Swift

on:
  push:
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - 'Tests/**'
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build_macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: brew install libsass
    - name: Build
      run: swift build -v
    - name: Tests
      run: swift test -v
